/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 11.09.2026 02:50:57

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1520;
#else
constexpr int kTensorArenaSize = 496;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,159 } };
const TfArray<1, float> quant0_scale = { 1, { 0.073538884520530701, } };
const TfArray<1, int> quant0_zero = { 1, { -41 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -171, 226, -79, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00026782864006236196, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  64, 15, 109, -106, -49, 57, 91, -116, -126, 106, 
  87, 74, -24, -74, -117, 10, 46, -86, 11, -46, 
  -112, -23, 127, 1, -109, -98, -115, -54, 117, 33, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0052310219034552574, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 117, 0, 0, -6, -108, 18, 45, -13, -29, -30, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00020302596385590732, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  45, -83, -73, 14, 106, 17, 121, -117, -5, -54, 46, 20, 66, 127, 58, -89, 0, -28, -83, 25, 
  -60, -122, 73, 72, 58, -44, -56, -104, -100, 20, -56, -57, 68, 24, 75, 96, -54, 37, -47, -33, 
  -24, -104, -3, 113, -52, -63, -38, 22, -44, -12, 35, 54, -23, -93, -14, -75, 90, -104, -107, -87, 
  67, 14, 101, 4, -70, 82, -60, -45, -32, 86, 88, 52, -60, -99, -5, -48, -14, -58, 124, 95, 
  -55, 64, -104, -46, -93, 75, -42, 25, -95, 59, 103, 61, -34, 47, 27, -102, -62, 108, 72, 56, 
  -93, 75, -75, 55, -33, -125, -6, 85, -125, -49, 83, 64, -55, 68, -26, -73, -40, 66, -72, 5, 
  98, 51, -63, -84, 85, 84, 10, -38, -22, -4, 89, 44, -93, -44, 10, -19, 53, -19, -26, -40, 
  -12, 98, 50, 66, -11, 92, 96, -115, 121, -24, -82, 121, 92, -26, -107, 54, 107, 6, 26, 95, 
  65, 44, 59, 44, 94, 36, -117, -30, -33, 12, 100, 23, -7, -114, -37, 102, -95, 76, -53, -37, 
  53, -77, -17, -2, 87, 108, -31, 24, 102, -111, -44, 52, -103, -59, 60, -20, -36, 95, -5, 88, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035678432323038578, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 156, 0, 0, 0, 19, 0, 29, -127, 26, -93, 256, 0, 186, 91, 0, 0, 204, 0, -100, -84, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00015890103532001376, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*159] = { 
  31, -1, -23, 81, 33, 43, 30, -45, 37, -57, 6, 37, -65, -47, -13, 80, 27, 66, -35, -33, 73, -22, 67, 13, -78, 49, -47, -48, -64, -79, 18, 25, 46, -72, -81, 36, -53, 60, -9, -58, 30, -16, -70, -30, -77, 64, -35, 67, -60, -66, -21, -85, 26, 12, -74, 54, 83, 59, 87, 57, 42, -22, 21, -46, -1, -48, 10, 34, 76, -4, 27, -65, -50, -24, -20, -48, 53, 33, -20, 60, 14, -14, -26, 15, -25, 1, -94, -19, -68, -80, 26, -25, -49, 61, -19, -90, 72, 39, -66, -37, -10, -89, 10, 35, -30, -41, -12, -5, -30, -31, 73, 18, -2, 50, -42, 76, -39, 23, -88, 23, 36, -5, 12, 71, -88, -21, 42, -7, 55, -23, -85, -64, 59, 7, 52, -59, -10, 67, -33, -10, 27, -13, -67, -61, -42, -30, -34, 27, -61, -55, -49, 37, -31, 38, 15, -44, 49, 5, -94, 
  -82, -6, 68, 10, -25, 14, 26, 25, 37, 77, -54, 35, 11, 15, 51, -45, 65, 41, 84, -50, -14, -8, 69, -16, 42, 40, -15, 60, -20, -61, -13, 78, 72, 81, 57, -26, -66, -8, 22, -38, -35, -46, 81, 59, 48, -22, 62, -58, 7, 0, -76, -10, 3, -31, -11, -84, -79, 66, 70, -67, -15, 57, -34, -14, -21, 1, 63, -83, 46, -22, 75, -47, 50, -5, 12, 68, -26, -47, -6, 75, -11, -84, -43, 0, 38, 6, -17, -61, 16, -20, 26, 26, 75, 19, 5, 47, -39, -69, 14, -74, 18, 80, -1, -12, -58, 39, 61, -53, -15, -15, -24, -73, 83, 25, -24, 73, 21, 17, -62, -58, 21, -78, -26, -43, 39, -7, -2, 32, -69, 78, -29, -24, 52, -25, 78, 51, -53, -26, -13, 52, -80, 12, -8, -37, 3, 52, 52, 40, -32, -49, -39, -29, -38, -32, -32, 59, 51, 76, -58, 
  54, -11, -72, -59, 36, -44, 51, 70, 80, -7, -63, 14, -61, 40, -49, 58, 27, 49, 1, 36, 83, -78, 46, -66, 10, -21, 80, 41, -43, -65, -42, 55, 43, -60, -16, -27, -72, -5, 48, -64, 43, 43, -78, -14, 30, -16, -43, -67, 30, -22, 43, -19, -15, -2, 44, -68, 9, 11, 10, -23, 77, -29, -13, 14, -23, 49, 17, -47, -25, -28, -4, -82, 6, 71, -14, -72, -71, 45, -41, -50, 35, -45, 30, -3, 7, 14, -21, -1, -66, 0, -59, 70, 19, -29, 83, 57, 26, 42, 29, 24, -81, -72, -43, -59, 38, -33, 74, 59, 7, -14, -40, 43, 6, -67, -52, -69, 40, 85, -19, 36, -42, 68, 84, -81, 73, 70, 22, 55, -70, -5, 47, -51, 16, 41, 42, 41, -41, 61, 49, 29, -12, 73, 77, 75, -68, 1, -70, 8, -30, 11, 36, -43, -28, 8, 33, 82, 47, -27, 66, 
  -69, 44, -44, 50, -7, 49, -8, 81, 41, -71, 68, 67, 41, 52, 36, -19, -64, -41, 28, 53, -55, 34, -54, -31, 51, 42, -60, 50, 70, 54, -37, 35, 70, -37, 51, 11, 82, -80, 16, 57, -69, 51, 1, 65, 80, -65, -4, -53, 50, 39, -55, -3, -16, -84, 20, -64, -72, -82, -34, -10, 75, 29, 79, 60, -56, -75, 47, -72, -53, -77, 48, -44, -45, -60, 18, 28, -21, 84, 30, 81, 17, 54, 58, -26, -16, -68, -7, -32, 51, -34, 34, 28, -69, 10, 69, -32, -50, -17, 65, -20, -27, -7, 67, -49, -40, -5, 10, -23, 15, 23, -70, 13, -3, 61, 5, 75, -76, 3, 58, -5, -78, 67, 3, 26, -70, 4, -1, -51, 21, 27, -32, -75, -22, 73, -16, -41, -55, 18, 7, 57, 51, 55, 21, -32, 15, 19, -35, -57, -28, -63, -22, -53, 67, 75, -53, 29, 30, 82, -46, 
  81, 9, 22, -54, -72, -61, 74, -14, -32, 57, -17, 22, -46, -31, -53, 51, 55, 61, -2, -14, -8, 77, -14, -11, -26, 4, 62, 58, -76, -65, 41, -51, 76, -59, -25, -38, -23, -76, 18, 47, 5, 20, -76, -31, 46, -52, 62, 50, -17, 56, 53, 60, -65, -8, -23, 87, 51, 60, 80, 57, -63, -58, 85, 86, 13, 54, -29, 90, -76, -14, -68, 24, 60, 32, 38, 42, -26, -22, -43, -36, 59, -84, 40, -59, 28, -47, 18, -62, 54, -30, -32, 3, 20, 53, 23, -1, 17, -16, -60, -64, -19, -75, 17, -27, 74, -45, -76, -31, -40, 27, -53, -4, -48, 0, 36, -3, -29, -55, -44, -9, 78, -22, -46, -7, -67, 5, 77, -65, -39, 33, -30, -16, 30, -18, -24, -23, 40, 42, -78, 57, 22, 11, 50, 5, 52, -85, 60, 12, -73, -76, -13, 39, -29, -58, 35, 81, 63, -49, 73, 
  -25, 63, 15, -4, -28, -66, 8, 84, -33, 18, -78, -30, -83, 39, 15, -1, -76, 24, -26, 7, -65, -69, -8, -42, 61, -22, 23, -12, -40, 83, -16, -9, 65, -51, 19, -78, 57, -49, 34, 73, 57, 32, -58, -23, 14, -82, -62, -56, -3, 53, 74, -12, 28, -34, 37, 50, 28, -10, 47, 6, 22, -80, 55, -66, -23, 0, -31, 67, 72, 38, 78, -38, 57, -62, -83, -54, -10, -13, 53, 0, -65, 31, -42, 66, -7, -64, 24, -5, 83, -15, 10, 6, -51, 65, 3, -7, -10, 27, -1, 51, -11, 25, 68, -48, 18, 14, 82, -56, 29, 46, -9, -7, 25, 48, 59, 16, 41, -65, 23, -52, -83, 46, -65, 12, 3, 78, -14, -32, -41, -76, 6, 28, -53, -29, 17, 73, 37, -65, 65, 77, 46, -2, 0, -47, 13, -47, 74, 77, 73, -40, 64, 21, 29, -76, 59, -6, -26, 64, -33, 
  65, -5, -55, -41, -46, -82, -26, 62, -26, 12, 2, -4, 5, 53, 38, -7, -28, -37, 88, 71, -34, 21, -33, 60, -28, -2, 91, -62, 74, 29, 63, -69, 9, -2, -57, 58, -67, 44, -58, 91, -4, 22, -2, 10, -36, -68, 85, -42, -6, -17, -53, 72, -70, 73, 24, -10, 8, 69, 49, -26, -48, 13, 64, -45, 45, 27, -70, 57, -59, -42, 18, 79, -20, 42, 28, 54, 43, 69, 39, -34, 66, 55, 8, 29, -44, -19, 58, 27, -32, -28, -52, 60, -27, 82, -22, -77, -34, -46, -71, -5, -46, -45, 7, -21, 83, -11, -1, -42, -70, -1, 0, 43, 53, -86, 20, -18, 48, -34, -73, -31, -46, 16, -70, 0, -31, -67, -7, 36, -24, -71, 34, -80, -9, 38, 55, 65, -69, 36, 59, 84, 32, 50, -31, -81, -60, 9, 58, -75, 66, 53, -59, 69, -7, 69, -36, -80, 12, -38, 54, 
  28, -103, 43, 60, 63, 25, 22, 32, -30, 66, -21, 77, -32, 30, -58, -87, -35, -51, -63, 70, 65, -57, -47, -7, -25, 75, -27, 18, -83, -18, 12, 69, 11, -83, -40, -90, -27, 8, 43, -40, -24, 17, 78, 72, 20, -16, 10, -75, -53, 40, -59, -23, -15, -20, -19, -53, -79, 55, 53, -87, -62, -33, 37, -67, 39, 18, 16, -38, -42, 81, -55, 11, -17, 35, 0, 14, -34, 47, -43, 40, 84, -81, 51, -2, 21, -81, 33, 34, 48, -39, -31, -82, 3, -54, -73, -39, -34, -80, -4, 70, -33, 45, -7, -75, -12, -30, -60, -83, 88, -39, -56, -61, 21, 44, 76, -29, 68, -6, -24, 39, -22, 29, -2, -64, 37, 35, -49, -60, -8, -7, 58, 5, -6, 24, -47, 59, -8, -11, 12, -1, -5, 52, 52, 67, 33, 56, 2, -57, 59, 21, 48, -31, 11, 54, 56, 31, -25, 17, -8, 
  15, 51, 71, -8, -60, 48, -15, -54, -10, -17, 0, 43, 42, -39, 3, -50, 22, -51, 71, 5, 65, 42, 59, 17, 35, 35, 44, -26, 51, -95, 23, -103, -36, -25, -90, -45, -96, 45, -82, -17, -68, -68, -100, -58, -99, 1, -51, -29, -60, 11, -93, -97, 68, -80, 35, 32, 18, 50, -17, -40, 45, -27, 65, -41, -2, -87, 64, 52, 43, -52, -43, -31, 8, -73, -33, -87, -75, -50, -57, 59, -51, -61, -82, -56, 53, -1, -22, 13, 29, 25, -22, -98, -97, -41, 41, -26, 53, -4, 15, -64, -77, -68, -55, 20, -8, 45, -32, -12, 33, 0, -24, 54, 14, 38, 65, 78, 25, -52, 70, -22, 58, 65, 1, -27, 42, -81, 12, 78, -80, 58, -81, 61, -87, -28, -64, -10, -70, 64, 11, 62, 62, -15, 48, -58, -77, 2, 25, -68, -87, -62, 62, 35, -53, -62, -44, 47, -86, -82, 42, 
  -91, 26, -68, -13, -55, 43, -87, -14, -61, -100, -85, -70, -98, -34, -64, 55, -19, 39, 50, -64, -23, 48, 14, 76, 83, 57, 7, 30, 2, 42, -36, -23, -57, 0, 61, 24, 57, 62, -11, 15, 26, 43, -39, 25, -30, -79, 59, 39, 76, -61, 47, 85, -77, -99, -40, 12, 46, 14, -87, 12, -91, -64, -77, 45, -16, -35, -92, -36, -68, 24, -65, 45, 66, -2, -18, -65, 78, -22, -79, 62, 47, 88, -62, -39, -53, 72, -49, -37, 45, 17, 69, 36, -19, -3, 19, 87, 5, -73, -61, -34, 55, -61, -68, -25, 17, 1, -97, -27, 14, 24, 34, -44, -36, -39, 66, 50, 62, 45, 55, 38, 64, -81, -39, 73, -46, 40, 64, -22, -35, 40, -30, -38, -18, -12, -60, 49, 84, 9, 23, -73, 75, -50, 39, 2, 16, 40, 87, 3, -74, 2, -73, -69, -35, -58, 78, -63, -59, 50, -66, 
  127, 37, 40, -61, -50, -41, 46, 13, -6, 27, -64, 25, 23, -63, 41, -42, 5, 4, 34, 21, -74, 41, -77, 68, 70, -15, -43, -27, 60, 62, -70, -53, -59, -10, 89, 82, -16, -52, -53, 32, 38, -6, 9, -16, -17, 67, 12, -78, 48, 27, -29, -56, -20, 38, 56, 73, -46, -41, 17, -11, 26, 33, 59, 64, 26, -77, -70, 40, 40, 27, 69, 8, -25, -44, -11, 71, 20, -58, 29, 76, -44, -66, 20, -60, -36, 57, -32, 18, -30, -37, 6, 84, 42, -41, -11, 1, -41, 38, -67, 43, 73, 51, 38, 33, 39, -43, 35, -81, 76, 16, -21, -12, 14, 27, -92, -1, -35, 55, -48, -62, -54, -84, -63, -76, 56, 25, -78, 2, 23, -91, 37, -53, -86, -100, 7, 11, -23, -89, 63, 36, -48, -73, -51, 15, -26, -95, -24, -45, 22, -45, -13, 35, 29, 58, -62, -66, -54, -9, -30, 
  -12, 28, 75, -25, -64, -75, 83, -33, 62, -20, 72, 77, 54, 76, -31, 38, -35, -30, 76, 2, -19, -18, 80, 3, 26, 33, 53, 41, 85, 32, -7, -18, 3, -34, 23, -19, -58, 21, 22, 45, 37, 60, 73, -13, -44, -26, 19, 39, -73, -7, -63, 57, 26, 28, 77, 48, 42, -15, 9, -67, 64, 45, -2, -23, 59, 50, 55, -21, -17, -19, -65, 3, -47, -50, 67, 23, 37, 68, 37, 14, 38, 76, -70, -45, -79, -75, -54, 39, -10, 54, 42, -66, -82, -63, 16, 24, 37, 55, -14, -23, -11, -5, 63, 59, 52, 32, 8, 82, 0, -71, -18, 18, 34, 26, -76, -55, -77, 6, 53, 30, 83, 75, 6, -17, -6, -22, -45, -63, 84, 62, -51, 50, 35, -17, -74, 18, -62, 63, -41, 48, -7, 11, -13, 36, 55, -76, 2, -34, -58, -43, 59, -48, -10, 7, -12, 30, 41, 85, -6, 
  -6, -49, -35, -13, 62, -95, -74, -107, -93, 15, -44, -99, -4, 23, -47, 49, -1, -40, 57, -36, 30, 41, -56, 53, 44, -20, 12, -31, 79, -12, -26, 30, -68, 91, 68, 68, 88, -33, -49, -33, 11, 33, -50, -23, -66, -19, 91, 55, -10, 80, 55, -74, -86, 46, -64, -102, -39, 46, -36, 15, -50, -84, -90, 30, -12, -4, 31, 7, -16, 37, -20, -59, 22, 41, 10, -91, -35, 61, -72, -71, 13, 41, 80, 61, 84, 74, -64, -35, 19, 66, -43, 94, 33, 31, -39, -61, 45, 22, 64, -15, -51, 52, 42, 27, 0, -70, 17, 104, -1, 28, 8, -48, -19, -65, -81, -11, -63, -48, 53, 21, 25, -28, 12, -63, 10, 18, -97, 32, -59, 60, -15, 37, 62, -11, 20, 72, 39, -8, 63, 82, 51, 17, 68, -21, -34, -24, -82, 56, -28, -85, 19, -65, -13, 16, -18, 68, -70, 37, -41, 
  53, -64, -66, 1, 77, 82, -68, 82, -7, 25, 21, 28, 80, 28, -10, -52, -77, -6, -61, -23, -60, -61, 1, -21, -29, -78, -52, 77, -9, 13, 35, -72, -55, -72, -3, 31, 49, 7, 81, -15, 86, 48, 76, -52, 79, -33, 3, 53, 88, 53, 30, 41, -60, -9, 74, -32, 16, 55, 47, -8, 8, -20, -6, -57, 62, 71, 74, 71, 21, 85, -64, -11, 56, -14, 41, -57, -41, -36, 40, -47, -34, 37, -24, -27, 48, 17, 64, 75, 2, -74, 15, 26, -49, 52, -75, -57, -30, 87, 9, -37, 21, 77, 24, -59, -48, 38, 19, -1, -30, 40, 54, -81, -56, 21, -58, 42, 44, -52, 43, -77, -6, -36, -42, -31, 72, 11, -72, 59, 25, 67, -75, -73, 13, -11, -77, -83, 31, -36, -43, 64, 67, -14, 44, -81, -26, 54, 34, -49, 43, 75, -35, -65, -68, -69, -17, 67, -55, -19, 47, 
  76, -71, -46, 16, 6, -50, -38, 28, 39, 28, 81, -84, -72, 81, -83, -33, -75, 11, 47, -67, 70, 81, -43, 61, -79, -50, -12, -69, 66, -24, 84, -46, -39, 51, -13, -56, -67, 19, 67, -78, -84, 68, -81, 54, -13, 51, -31, -54, -82, -36, -17, 37, 27, -15, -64, -55, 75, -21, 72, -48, 5, 35, -51, 76, 12, 75, 72, 52, -15, 44, 8, -52, 75, -34, 72, 40, -36, 21, -3, 7, 44, 9, -57, -40, 15, -67, 63, 7, -70, 16, -38, 26, -13, 47, -72, -2, 65, 65, 67, 85, -78, 77, -55, 61, -70, -30, 52, -75, -33, -50, -38, -2, 81, 44, -77, 51, 82, -72, 63, 69, -43, -12, -9, -50, -59, -66, -6, 79, 76, -56, -29, -51, -3, -3, 57, 43, 77, 38, -71, 67, -28, 32, -27, -43, 58, 56, 30, -52, 48, 60, -26, -60, 64, 54, 44, -47, -26, 48, -24, 
  0, 71, -63, -79, -79, 23, -10, 14, 31, 28, -5, 32, -47, 39, 40, 65, 14, 37, 29, 50, -77, 70, -69, 37, 19, 1, -37, -31, -16, -46, 22, -29, -30, 44, -6, 18, 0, -78, 21, 74, 48, -40, 25, -60, 59, -52, -76, -21, -61, 58, 35, -7, 59, 71, 34, -48, 73, 37, -61, 70, 2, -52, 16, -36, 13, 34, 13, -50, 7, 54, -72, 69, 68, 73, 35, 60, -35, 19, 71, 31, -59, -49, 11, 79, 84, 64, 8, 43, 48, 84, -3, 83, 17, 53, 80, 59, -69, 41, 44, 38, 64, 73, 80, -26, 57, -53, 13, 33, 83, -48, 25, -71, -82, 15, 49, -53, -29, -73, -3, -9, -45, 17, -11, -30, 31, -20, -49, -39, -24, -63, -15, -25, 17, 71, -56, -34, -46, -25, 10, 12, -45, 25, -35, -6, 69, 14, 80, 10, -6, -65, 41, -30, -35, 65, 51, 34, -41, 57, -42, 
  35, -36, -54, 8, 79, -30, -37, -69, 22, -81, -81, -34, 13, 35, -35, 28, -70, -46, 33, -30, -77, -54, 25, -40, 31, -32, -22, 60, -61, 61, 32, 2, 67, -47, -22, -41, 28, -67, -31, 7, 2, -13, 15, 65, -5, -65, 66, -79, -10, -39, 1, -17, -22, -29, -11, -89, -1, -10, 46, -66, -61, 66, -56, 0, -65, 32, -5, -38, -9, 73, -76, -23, -52, 62, 51, 35, -47, 13, -61, 7, 9, 66, -91, -32, -8, 53, 0, -55, 80, -18, 13, 83, 78, 14, 13, -43, 9, -23, 76, -40, -13, -14, -18, -17, 68, 54, 64, 86, -31, -36, 56, 7, 45, -92, -90, 15, -35, 60, -63, -85, 27, -26, -64, -23, 66, 5, -23, -90, 61, 62, -30, 52, -30, 3, -72, -12, 44, -71, 68, -86, 58, -30, 38, -41, -53, 16, 67, 40, -13, 4, -55, -24, 50, 25, -17, -54, 24, 56, -72, 
  -16, 41, 75, 59, 61, -26, -33, 70, 29, -11, -30, 82, -30, 60, -60, -28, -59, 22, 77, -46, 45, -36, -62, 83, -45, -65, -42, 27, -6, -49, -11, -64, 3, 21, 8, 83, 80, -45, 59, -71, -80, -25, 84, -26, 25, -55, 8, 80, -64, 41, -39, -49, 78, 44, 24, -63, 63, -73, -18, -40, 25, -66, 41, 79, -17, 44, -9, 2, 27, -24, 64, -31, 54, 77, 39, 20, -68, -63, 62, -65, -68, -77, -74, 14, 44, 78, -33, 19, 19, 37, -1, 81, -78, -43, 60, 44, 36, -30, 75, -77, 73, 34, 6, -51, -48, -85, -67, 79, 23, -83, -76, -39, 65, 3, -57, 25, 58, 82, -42, -12, -51, 77, 22, 74, 2, 36, 38, 71, 79, 73, 43, 36, -51, 66, 6, -17, 79, 50, 18, -18, -84, -77, -78, 58, 43, -2, 24, 35, 71, -5, 41, 70, -82, -61, 24, -23, -18, 32, 34, 
  -102, -39, 55, -88, 38, 4, -61, -16, -12, -40, -87, -41, -82, -69, -72, -55, -5, -60, -56, 21, -48, 63, -52, 59, -44, -79, -6, -26, -78, -63, 30, -46, -60, -84, 75, 56, 14, -69, -76, -37, -66, 13, -54, 37, -5, -19, 79, 15, -70, -78, 3, -72, 37, -78, 54, -64, -55, -45, -32, 49, -39, -58, -69, 52, 29, -56, 62, -78, -5, 63, 41, 36, 58, -42, -83, 21, 71, 13, -24, 28, 25, 38, 75, -2, 39, 13, 70, 8, -9, -75, -88, 60, 48, -30, -62, -61, 42, 13, 73, -56, -89, 80, 17, 7, -43, 1, -62, -59, -4, 43, -58, 14, -80, -42, -47, -63, 37, 38, -70, -74, 73, -44, -20, 17, 25, 83, -12, -29, 11, 11, -67, -29, 15, 6, -3, -37, 29, 89, -30, 31, 66, -22, -8, -34, 73, 68, 27, 33, -9, -16, 0, 35, 72, 42, 4, -33, 48, -26, 85, 
  -31, 41, 17, -44, -11, -29, 21, -16, 56, 52, -74, 60, 52, -8, -10, -47, -14, -82, -56, 11, -39, -86, 57, -77, -16, -8, -61, -44, 20, 53, -75, -6, 55, -69, -7, 13, -93, 0, -14, -28, -71, -73, 7, 30, -17, -84, -93, 11, -17, -3, 14, 32, -78, 1, 38, -48, 46, -61, -64, 61, -76, 46, -71, 20, -72, -19, -23, -65, -69, -59, -89, 49, -28, -13, -20, 23, -77, -86, -75, -40, 63, -8, -8, -78, -26, 20, 65, -16, 13, -13, -93, -1, -70, -31, 12, -79, -70, -76, 68, -62, -38, 54, 49, -72, -23, 46, -98, -66, -4, 49, 88, 67, -67, -49, 40, 14, -7, -42, -32, -3, 86, 15, 38, -39, 27, 57, -71, 5, -39, 4, -54, 8, 77, 55, 16, 86, 42, 68, -44, -33, 35, -54, 30, 19, 1, 66, -58, 66, -19, 30, -85, 40, -19, -29, 9, -70, -60, -10, 1, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,159 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0021607757080346346, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.056904394179582596, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.051200058311223984, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.035460002720355988, } };
const TfArray<1, int> quant9_zero = { 1, { 127 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 159, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3180, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 160), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1110361_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1110361_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1110361_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1110361_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1110361_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
